// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI.Infrastructure.DatabaseContext;

#nullable disable

namespace MinimalAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230813173635_AddingKey")]
    partial class AddingKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI.Core.Domain.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("7f335988-2af0-4718-9198-daadbfd45b54"),
                            ProductName = "Chair",
                            ProductPrice = 82.900000000000006,
                            ProductQuantity = 6
                        },
                        new
                        {
                            ProductId = new Guid("0358c277-0720-483a-8ba8-261620be5f3c"),
                            ProductName = "Dining Table",
                            ProductPrice = 322.94,
                            ProductQuantity = 1
                        },
                        new
                        {
                            ProductId = new Guid("767ad7f1-cb29-45bc-8d6d-5b92a7542b4f"),
                            ProductName = "Table Cloth",
                            ProductPrice = 62.0,
                            ProductQuantity = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
