// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI.Infrastructure.DatabaseContext;

#nullable disable

namespace MinimalAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230813174347_AddingID")]
    partial class AddingID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI.Core.Domain.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("3e679362-8bb1-42f7-95d2-0da5a620265f"),
                            ProductName = "Chair",
                            ProductPrice = 82.900000000000006,
                            ProductQuantity = 6
                        },
                        new
                        {
                            ProductId = new Guid("a8a46194-525f-448d-b274-5a0551c84419"),
                            ProductName = "Dining Table",
                            ProductPrice = 322.94,
                            ProductQuantity = 1
                        },
                        new
                        {
                            ProductId = new Guid("02eebf2b-ab51-4ea5-b2f7-0c2d288a384b"),
                            ProductName = "Table Cloth",
                            ProductPrice = 62.0,
                            ProductQuantity = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
