// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI.Infrastructure.DatabaseContext;

#nullable disable

namespace MinimalAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230813100827_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI.Core.Domain.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("f44ffc65-3aa7-451b-8411-167f9b87b182"),
                            ProductName = "Chair",
                            ProductPrice = 82.900000000000006,
                            ProductQuantity = 6
                        },
                        new
                        {
                            ProductId = new Guid("1c01ac57-153f-467a-b7c4-f82335692b4c"),
                            ProductName = "Dining Table",
                            ProductPrice = 322.94,
                            ProductQuantity = 1
                        },
                        new
                        {
                            ProductId = new Guid("7eefe19f-6334-46b2-acc6-80e71ad215a3"),
                            ProductName = "Table Cloth",
                            ProductPrice = 62.0,
                            ProductQuantity = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
